### ISSUE TITLE
convert can't handle conditional `track_features:` (in onednn-feedstock)

### ISSUE THREAD

**Issue by mgorny** [conda-incubator/conda-recipe-manager#273] opened 2024-12-17 11:22 UTC
**What happened?**
When trying to convert conda-forge/onednn-feedstock@15fa3b7a7108feb8eac4a9aee401956911e72580, I'm getting:

```
$ conda-recipe-manager  convert --debug recipe/meta.yaml  
EXCEPTION: An exception occurred while parsing the recipe file
list index out of range
0 errors and 0 warnings were found.
```

FWICS, the problem is:

```yaml
      {% if dnnl_cpu_runtime != "omp" %}
      track_features:
        - onednn-{{ dnnl_cpu_runtime }}
      {% endif %}
```

https://github.com/conda-forge/onednn-feedstock/blob/15fa3b7a7108feb8eac4a9aee401956911e72580/recipe/meta.yaml#L24-L27

(I'm guessing that because changing it to:

```yaml
      track_features:
        - onednn-{{ dnnl_cpu_runtime }}  # [dnnl_cpu_runtime != "omp"]
```

makes the problem go away)

**To Reproduce**

```
git clone https://github.com/conda-forge/onednn-feedstock
cd onednn-feedstock
git checkout 15fa3b7a7108feb8eac4a9aee401956911e72580
conda-recipe-manager convert recipe/meta.yaml
```

**Additional Details (please complete the following information):**
 - OS: Gentoo Linux amd64
 - Conda Recipe Manager version: 0.4.0, also reproduced with e2bf2cbf67492fc1b766a2e2360488f4a2dc533b
 - Any other context about the problem that was found.

**Comment by schuylermartin45** [comment] 2024-12-17 15:53
I am going to mark this as a duplicate of #258 and close the issue. But thank you so much for reporting this with such detail! I really appreciate it.

Parsing and handling these conditional and loop macros is a non trivial amount of work, especially given we are trying to move to a format that forbids them entirely. If I wasn't so resource constrained, I might feel differently.

The data I've collected also suggests that there really aren't that many recipes that use these kinds of macros. BUT I'm so glad you used a selector as a work around! I speculate that most of these `ifdefs` can be manually converted to a selector before running `convert` faster than it would take to implement full parsing support.

Now that I've said that out loud, maybe there's a hacky work around where we don't fully parse the macros. It'll likely be some nasty regex solution, but that might offer some middle ground solution. I'll make a note in the other ticket.

**Closed by schuylermartin45** 2024-12-17 15:53 UTC
Labels: bug, duplicate

**Comment by mgorny** [comment] 2024-12-17 16:18
Ah, sorry, I really should have searched for `if` 🤦.

**Comment by schuylermartin45** [comment] 2024-12-17 16:38
No worries, happens to me all the time!
